# Generated by Django 2.2.3 on 2019-10-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo_main', '0015_auto_20191002_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pred_three',
            name='exports_mean',
        ),
        migrations.RemoveField(
            model_name='pred_three',
            name='imports_mean',
        ),
        migrations.RemoveField(
            model_name='pred_three',
            name='production_mean',
        ),
    ]
